# Generated by Django 6.0 on 2025-12-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRamon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='competencias/'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/'),
        ),
        migrations.AddField(
            model_name='manager',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='managers/'),
        ),
    ]
